### ISSUE TITLE
Broken Files?

### ISSUE THREAD

**Issue by Blizihguh** [Jocker666z/vgm2flac#1]
Hey there. Yesterday I went through a bunch of music rips from vgm.hcs64.com, and while this script worked for the majority of them, there were a few that didn't seem to work. It's entirely possible that I messed up installing one of the dependencies, but I couldn't find any indication of what, so I figured I'd write an issue about it. I'm not going to die if I don't get those flacs or anything, but maybe documenting it will turn out to be helpful to someone.

For reference, I did this all on Linux Mint. I didn't bother installing uade, since the warning message implied it would only be a problem with Amiga files. I believe I had everything else installed. This was running off of a Live USB, so pretty much the freshest possible environment -- no lingering old versions of any dependencies.

Rips that refused to encode at all:
Katamari Damacy [PS2, .vgmstream]
We Love Katamari [PS2, .MIB/.ss2]
Persona 4 The Golden [PC, .txtp]

Rips that partially failed:
Earthbound [SNES, .spc; around 50% success]
MGSV [PS3, .wem; around 75% success, although one file got corrupted halfway through. Specifically d30a053a1cd3c45.wem, which is Take On Me]

In both of the partial failure cases, the console output had some files that said they encoded to wav successfully, but unfortunately I couldn't find the wav outputs for those files, only the ones that correctly converted to flac. In the case of MGSV specifically, all of the files that failed had supposedly converted to wav successfully, so not being able to find them was pretty sad.

I had other rips involving .spc files work fine (eg Street Fighter II Turbo). I got vgmstream from their repo, which has releases for vgmstream-cli that are claimed to work natively on Linux. Not sure which dependencies handle the other file formats. It might be useful to enumerate which are which in the README, since there are so many optional dependencies.

At any rate, thanks for the useful tool. Quite happy with the results for everything else I ran through it, and it was pretty easy to get going :)

**Comment by Jocker666z** [comment]
Hi, I'm a bit confused, indeed I just tested all the rips you mentioned, and all of them work on my machine (Debian Unstable). 


I need more information, I need you to give me the error logs by running `vgm2flac -v`. That would help me.

**Comment by Jocker666z** [comment]
I have added a dependency test, you can run it and give me the result by doing a `vgm2flac -d`

**Comment by Jocker666z** [comment]
INo answer, I close the commit
