### ISSUE TITLE
XA files not recognized

### ISSUE THREAD

**Issue by GUUser91** [Jocker666z/vgm2flac#2]
I tried vgm2flac on a folder containing xa and psf files and only the psf files were recognized.
Here's a 7zip file containing the xa files.
https://psf.joshw.info/g/Gundam%20Battle%20Assault%202%20(2002-07-17)(Natsume)(Bandai)%5bPS1%5d.7z

**Comment by Jocker666z** [comment]
for XA, vgmstream must be compiled with ffmpeg lib, see https://github.com/vgmstream/vgmstream/blob/master/doc/BUILD.md or readme of vgm2flac (I just updated the readme).

`libavformat-dev libavcodec-dev libavutil-dev libswresample-dev`
